/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BinaryOptionsNoLockInterface extends ethers.utils.Interface {
  functions: {
    "binToEther(uint256,uint256)": FunctionFragment;
    "buy(bool)": FunctionFragment;
    "collect()": FunctionFragment;
    "collectedOptions(address,uint256)": FunctionFragment;
    "ehterToBin(uint256,uint256)": FunctionFragment;
    "executeRound(uint32)": FunctionFragment;
    "getBinSupply()": FunctionFragment;
    "getCollateral()": FunctionFragment;
    "getCollectedOptionsLength(address)": FunctionFragment;
    "getEthPrice()": FunctionFragment;
    "getOptionsLength()": FunctionFragment;
    "getPayOut(uint32,bool)": FunctionFragment;
    "getPendingOptionsLength(address)": FunctionFragment;
    "getPrice(uint256)": FunctionFragment;
    "getReadyToCollect()": FunctionFragment;
    "options(uint256)": FunctionFragment;
    "pendingOptions(address,uint256)": FunctionFragment;
    "place(uint32,uint256,bool,bool)": FunctionFragment;
    "rounds(uint32)": FunctionFragment;
    "sell(uint256,bool)": FunctionFragment;
    "token()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "binToEther",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "buy", values: [boolean]): string;
  encodeFunctionData(functionFragment: "collect", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collectedOptions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ehterToBin",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBinSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectedOptionsLength",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayOut",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingOptionsLength",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReadyToCollect",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "options",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOptions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "place",
    values: [BigNumberish, BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(functionFragment: "binToEther", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "collect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectedOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ehterToBin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBinSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectedOptionsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingOptionsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReadyToCollect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "options", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "place", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;

  events: {
    "Bought(address)": EventFragment;
    "Collect(address)": EventFragment;
    "Execute(uint32)": EventFragment;
    "Place(address,uint32)": EventFragment;
    "Sold(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Bought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Collect"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Execute"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Place"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Sold"): EventFragment;
}

export class BinaryOptionsNoLock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BinaryOptionsNoLockInterface;

  functions: {
    binToEther(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "binToEther(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    buy(
      lock: boolean,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "buy(bool)"(
      lock: boolean,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    collect(overrides?: Overrides): Promise<ContractTransaction>;

    "collect()"(overrides?: Overrides): Promise<ContractTransaction>;

    collectedOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "collectedOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    ehterToBin(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ehterToBin(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    executeRound(
      timeStamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeRound(uint32)"(
      timeStamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getBinSupply(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getBinSupply()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getCollateral(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getCollateral()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getCollectedOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getCollectedOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getEthPrice(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getEthPrice()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getOptionsLength(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getOptionsLength()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getPayOut(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPayOut(uint32,bool)"(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getPendingOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPendingOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getPrice(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPrice(uint256)"(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getReadyToCollect(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    "getReadyToCollect()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    options(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      price: BigNumber;
      higher: boolean;
      execute: number;
      amount: BigNumber;
      id: number;
      payout: BigNumber;
      buyer: string;
      winner: boolean;
      0: BigNumber;
      1: boolean;
      2: number;
      3: BigNumber;
      4: number;
      5: BigNumber;
      6: string;
      7: boolean;
    }>;

    "options(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      price: BigNumber;
      higher: boolean;
      execute: number;
      amount: BigNumber;
      id: number;
      payout: BigNumber;
      buyer: string;
      winner: boolean;
      0: BigNumber;
      1: boolean;
      2: number;
      3: BigNumber;
      4: number;
      5: BigNumber;
      6: string;
      7: boolean;
    }>;

    pendingOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "pendingOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    place(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "place(uint32,uint256,bool,bool)"(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      executed: boolean;
      options: number;
      price: BigNumber;
      higherAmount: BigNumber;
      lowerAmount: BigNumber;
      0: boolean;
      1: number;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
    }>;

    "rounds(uint32)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      executed: boolean;
      options: number;
      price: BigNumber;
      higherAmount: BigNumber;
      lowerAmount: BigNumber;
      0: boolean;
      1: number;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
    }>;

    sell(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sell(uint256,bool)"(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    token(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "token()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  binToEther(
    amount: BigNumberish,
    price: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "binToEther(uint256,uint256)"(
    amount: BigNumberish,
    price: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buy(
    lock: boolean,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "buy(bool)"(
    lock: boolean,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  collect(overrides?: Overrides): Promise<ContractTransaction>;

  "collect()"(overrides?: Overrides): Promise<ContractTransaction>;

  collectedOptions(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  "collectedOptions(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  ehterToBin(
    amount: BigNumberish,
    price: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "ehterToBin(uint256,uint256)"(
    amount: BigNumberish,
    price: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  executeRound(
    timeStamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeRound(uint32)"(
    timeStamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getBinSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "getBinSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCollateral(overrides?: CallOverrides): Promise<BigNumber>;

  "getCollateral()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCollectedOptionsLength(
    wallet: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getCollectedOptionsLength(address)"(
    wallet: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEthPrice(overrides?: CallOverrides): Promise<BigNumber>;

  "getEthPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

  getOptionsLength(overrides?: CallOverrides): Promise<BigNumber>;

  "getOptionsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  getPayOut(
    timeStamp: BigNumberish,
    higher: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPayOut(uint32,bool)"(
    timeStamp: BigNumberish,
    higher: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPendingOptionsLength(
    wallet: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPendingOptionsLength(address)"(
    wallet: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPrice(
    amountTobuy: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPrice(uint256)"(
    amountTobuy: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getReadyToCollect(
    overrides?: CallOverrides
  ): Promise<{
    0: BigNumber;
    1: BigNumber;
  }>;

  "getReadyToCollect()"(
    overrides?: CallOverrides
  ): Promise<{
    0: BigNumber;
    1: BigNumber;
  }>;

  options(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    price: BigNumber;
    higher: boolean;
    execute: number;
    amount: BigNumber;
    id: number;
    payout: BigNumber;
    buyer: string;
    winner: boolean;
    0: BigNumber;
    1: boolean;
    2: number;
    3: BigNumber;
    4: number;
    5: BigNumber;
    6: string;
    7: boolean;
  }>;

  "options(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    price: BigNumber;
    higher: boolean;
    execute: number;
    amount: BigNumber;
    id: number;
    payout: BigNumber;
    buyer: string;
    winner: boolean;
    0: BigNumber;
    1: boolean;
    2: number;
    3: BigNumber;
    4: number;
    5: BigNumber;
    6: string;
    7: boolean;
  }>;

  pendingOptions(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  "pendingOptions(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  place(
    timeStamp: BigNumberish,
    amount: BigNumberish,
    higher: boolean,
    doCollect: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "place(uint32,uint256,bool,bool)"(
    timeStamp: BigNumberish,
    amount: BigNumberish,
    higher: boolean,
    doCollect: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  rounds(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    executed: boolean;
    options: number;
    price: BigNumber;
    higherAmount: BigNumber;
    lowerAmount: BigNumber;
    0: boolean;
    1: number;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
  }>;

  "rounds(uint32)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    executed: boolean;
    options: number;
    price: BigNumber;
    higherAmount: BigNumber;
    lowerAmount: BigNumber;
    0: boolean;
    1: number;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
  }>;

  sell(
    amount: BigNumberish,
    fromLock: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sell(uint256,bool)"(
    amount: BigNumberish,
    fromLock: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  "token()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    binToEther(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "binToEther(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(lock: boolean, overrides?: CallOverrides): Promise<void>;

    "buy(bool)"(lock: boolean, overrides?: CallOverrides): Promise<void>;

    collect(overrides?: CallOverrides): Promise<void>;

    "collect()"(overrides?: CallOverrides): Promise<void>;

    collectedOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    "collectedOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    ehterToBin(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ehterToBin(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executeRound(
      timeStamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeRound(uint32)"(
      timeStamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBinSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "getBinSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    "getCollateral()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectedOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCollectedOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEthPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getEthPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOptionsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "getOptionsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPayOut(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPayOut(uint32,bool)"(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendingOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPendingOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrice(uint256)"(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReadyToCollect(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    "getReadyToCollect()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
      1: BigNumber;
    }>;

    options(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      price: BigNumber;
      higher: boolean;
      execute: number;
      amount: BigNumber;
      id: number;
      payout: BigNumber;
      buyer: string;
      winner: boolean;
      0: BigNumber;
      1: boolean;
      2: number;
      3: BigNumber;
      4: number;
      5: BigNumber;
      6: string;
      7: boolean;
    }>;

    "options(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      price: BigNumber;
      higher: boolean;
      execute: number;
      amount: BigNumber;
      id: number;
      payout: BigNumber;
      buyer: string;
      winner: boolean;
      0: BigNumber;
      1: boolean;
      2: number;
      3: BigNumber;
      4: number;
      5: BigNumber;
      6: string;
      7: boolean;
    }>;

    pendingOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    "pendingOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    place(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "place(uint32,uint256,bool,bool)"(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      executed: boolean;
      options: number;
      price: BigNumber;
      higherAmount: BigNumber;
      lowerAmount: BigNumber;
      0: boolean;
      1: number;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
    }>;

    "rounds(uint32)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      executed: boolean;
      options: number;
      price: BigNumber;
      higherAmount: BigNumber;
      lowerAmount: BigNumber;
      0: boolean;
      1: number;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
    }>;

    sell(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "sell(uint256,bool)"(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    "token()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    Bought(from: string | null): EventFilter;

    Collect(from: string | null): EventFilter;

    Execute(timeStamp: null): EventFilter;

    Place(from: string | null, timeStamp: null): EventFilter;

    Sold(from: string | null): EventFilter;
  };

  estimateGas: {
    binToEther(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "binToEther(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(lock: boolean, overrides?: PayableOverrides): Promise<BigNumber>;

    "buy(bool)"(
      lock: boolean,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    collect(overrides?: Overrides): Promise<BigNumber>;

    "collect()"(overrides?: Overrides): Promise<BigNumber>;

    collectedOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collectedOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ehterToBin(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ehterToBin(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executeRound(
      timeStamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeRound(uint32)"(
      timeStamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getBinSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "getBinSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    "getCollateral()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectedOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCollectedOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEthPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getEthPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOptionsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "getOptionsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPayOut(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPayOut(uint32,bool)"(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendingOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPendingOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrice(uint256)"(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReadyToCollect(overrides?: CallOverrides): Promise<BigNumber>;

    "getReadyToCollect()"(overrides?: CallOverrides): Promise<BigNumber>;

    options(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "options(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    place(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "place(uint32,uint256,bool,bool)"(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    rounds(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "rounds(uint32)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sell(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sell(uint256,bool)"(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    "token()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    binToEther(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "binToEther(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buy(
      lock: boolean,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "buy(bool)"(
      lock: boolean,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    collect(overrides?: Overrides): Promise<PopulatedTransaction>;

    "collect()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    collectedOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collectedOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ehterToBin(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ehterToBin(uint256,uint256)"(
      amount: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executeRound(
      timeStamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeRound(uint32)"(
      timeStamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getBinSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBinSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollateral(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCollateral()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollectedOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCollectedOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEthPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getEthPrice()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOptionsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getOptionsLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPayOut(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPayOut(uint32,bool)"(
      timeStamp: BigNumberish,
      higher: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPendingOptionsLength(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPendingOptionsLength(address)"(
      wallet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPrice(uint256)"(
      amountTobuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReadyToCollect(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getReadyToCollect()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    options(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "options(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingOptions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingOptions(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    place(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "place(uint32,uint256,bool,bool)"(
      timeStamp: BigNumberish,
      amount: BigNumberish,
      higher: boolean,
      doCollect: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    rounds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "rounds(uint32)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sell(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sell(uint256,bool)"(
      amount: BigNumberish,
      fromLock: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "token()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
